### ISSUE TITLE
Racy sync.Map usage

### ISSUE THREAD

**Issue by tv42** [timestee/idleaf#1]
https://github.com/timestee/idleaf/blob/8fd5364f3456433a6a7142da5e3346050860b518/idleaf.go#L37-L42

should use https://golang.org/pkg/sync/#Map.LoadOrStore

**Comment by timestee** [comment]
@tv42 If use `LoadOrStore`, then we need new a `Leaf` struct every time when `GenId` called.
I prefer to use `LoadOrStoreByCreator` like this:
```golang
LoadOrStoreByCreator(key interface{}, creator func() interface{}) (actual interface{}, loaded bool)
```
LoadOrStoreByCreator should return the existing value for the key if present. Otherwise, call the `creator` and store the returned value.

now i use `singleflight` to  make sure only one execution is in-flight to construct a new  domain leaf struct.

**Comment by tv42** [comment]
You can do a Load first and only wastefully create that struct on a racing LoadOrStore.

**Comment by timestee** [comment]
https://github.com/timestee/idleaf/blob/224ae68b9e224cc708a706260dc7bfe331c8f8dd/idleaf.go#L37-L57



`genid` will be  called in servial goroutines at the same time, even using `Load` and  `LoadOrStore` can not guarantee that the `domain leaf`  should be  created only once, but using singleflight will be ok.
